### ISSUE TITLE
require unleashes Zalgo

### ISSUE THREAD

**Issue by dkebler** [tufan-io/fs-read-data#2]
Hmmm...

https://github.com/tufan-io/fs-read-data/blob/2b02fe7bbcd443b83a14f5c374d8c719e7af7993/src/index.ts#L54

I mistakenly thought that you parsed the js file after reading it async but you just used require.  :-( which is sync.   Definitely need this async as it's a runtime call.

It's causing issues for me already in my app. 

Not sure how to do this but maybe read/toString and then acorn parse?

**Comment by sramam** [comment]
Can you describe how you expect this to work better?

It's a reasonably tall order to read, parse and interpret javascript - an unenviable collection of complexity and security concerns.

**Comment by mk-pmb** [comment]
We should make the read function accept a config object that configures supported filename extensions and their parsers. That way we could

```javascript
async function safeSandboxedImportJs(path) {
  return '… sandbox action here …';
}

await read({
  parsers: {
    js: safeSandboxedImportJs,
  },
}, filename);

// or pretend it's entirely unsupported:
await read({
  parsers: {
    js: false,
  },
}, filename);
```

Options object first to allow `fileNames.map(read.bind(null, opts))`.

**Comment by mk-pmb** [comment]
On the other hand, maybe it's not such a good idea to support `.js` by default, because the package name makes it look mostly safe, as in, I wouldn't have expected a code injection attack vector from this.

**Comment by mk-pmb** [comment]
I just discovered we use TypeScript here, so unfortunately someone else will have to implement it.

**Comment by dkebler** [comment]
I like the flexibility of the js import as I could bake in some simple computations into my otherwise plain object config file that ran at 'read'.  All the other formats are 'static'. For the time being I just put in a little promise delay to keep Zalgo in his box.  Works but obviously not a proper solution.

@mk-pmb, I'm in the same boat given I'm not a fan of preprocessors nor strong typing. So won't be jumping in for a pr :(

**Comment by dkebler** [comment]
I suppose I should comment that if the intention was only to allow a 'static' json object in js format then maybe support for .js should be removed as one could easily convert .js to json or other formats beforehand.  At the very least the readme should make it clear that using .js is "sync only" and does NOT support anything but a plain object in js.    

When I saw .js was supported I immediately supposed that I could include some built in code functionality to the otherwise "static data" file (see below).   I liked this package for its flexibility to handle any format without any thought on my part so I just assumed it was that flexible.  Maybe this functionality is beyond this package and could be added by extending this package? (which could be done without ts :+1:)  ).

below is an example where I threw in a .cond property in a yaml file that contains a js function as a string that allows me to evaluate this (sandboxed i.e. no context) condition in my code based on this custom condition set in this "static" config file.  This config file is part of an application 'plugin' not written by me so no way to a priori hard code these conditions into my app.  So yes I can do this with a yaml file but much easier to do this using a .js file.

```
    depHardware:
      - device: interrupt
        cond: 'hw => hw.usage.includes(''int'')? true : false'
        deploy: bus #property of mcp defive of where to deploy dep hardware, if not set will be same as mcp location
```

I'm going to close this but please @sramam at least make it clear in the readme (if you are not going to remove the .js support) that it is 'sync only' and only with a plain object.  To make that enforced I suggest you check that the resulting object from the require is indeed a plain object before proceeding.  https://www.npmjs.com/package/is-plain-object

**Comment by sramam** [comment]
ooh - this is way out of scope for the library. It was always meant to be a file reader, not a file interpreter. Parsing, evaluating/interpreting was always going to be some other library's concern.
The intent was only to wrap other libraries.

With the passage of time, I've grown to think this might not have been the hottest idea -
meaning, I tend to support JSON/YAML/js in my applications but typically don't like the "weight" 
of the other formatters in my code, so I write custom code and move on. Additionally I prefer to 
use a schema to validate the data when I can. This is especially valuable when data is coming in
from un-trusted 3rd parties. 

I'm still not sure why sync/async is a problem. Config files are typically very small, leaded in-
frequently and should not be causing a performance hit. 

More than likely I don't understand your use case. 

I might be open to considering the newer [dynamic import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#Dynamic_Imports), but not sure it's of much value if even you are moving away from this library. 

Thanks for taking this library out for a spin...

**Comment by mk-pmb** [comment]
Meanwhile I [rolled my own](https://github.com/mk-pmb/read-data-file-node) with no code execution by default.

Sync file system access is a problem when you use network file systems that might block for several minutes in failure cases. That doesn't play well with any interactive stuff. Think of a photo gallery plugin for a webserver, that tries to read picture descriptions from the directory specified in a request. If that resides on a network storage that isn't responding, it would be all well to have a timeout promise wrapper and give an error message after a few seconds. It would not be ok to make ALL currently pending requests to that webserver time out, and prevent answering the `/healthcheck` route for several minutes.

**Comment by sramam** [comment]
> Meanwhile I rolled my own with no code execution by default.
Glad you found a way out of it. I'd have been happy to hand ownership of the module to you if desired...

For .js files, as you have found, there are no easy answers I'm afraid.
